### PR TITLE
Methods

### PR DESCRIPTION
**Pull request by tmampa**
In this project, we implement our own version of Ruby’s enumerable methods.
-me each
- my each with index
- my all?
- my any
- my count
- my map
- my inject
-

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @tmampa and @emmyobonyo :wave: 

Kudos! 👏 Your custom enumerable methods pass more than half of the test cases
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED
Some of your custom enumerable methods are failing some tests cases. They're expected to produce the exact same result as ruby enumerable methods.


### The summary below should help you understand what you need to work on to fix your custom enumerable methods
* [ ] #my_each returns an Enumerator if no block is given
* [ ] #my_each_with_index returns an enumerator if no block is given
* [ ] #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self
* [ ] #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
* [ ] #my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
* [ ] #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
* [ ] #my_select returns an array containing all elements of enum for which the given block returns a true value
* [ ] #my_select returns an array containing all elements of enum for which the given block returns a true value::range
* [ ] #my_select returns an enumerator if no block is given
* [ ] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
* [ ] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
* [ ] #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
* [ ] #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
* [ ] #my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex
* [ ] #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
* [ ] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
* [ ] #my_any? returns true if the block ever returns a value other than false or nil
* [ ] #my_any? returns false if the block ever returns a value false or nil
* [ ] #my_any? returns false if the block ever returns a value false or nil::range
* [ ] #my_any? does not mutate the original array
* [ ] #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
* [ ] #my_any? when no block or argument is given returns false if at least one of the collection is not true
* [ ] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
* [ ] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
* [ ] #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
* [ ] #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
* [ ] #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
* [ ] #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
* [ ] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
* [ ] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
* [ ] #my_none? when a class is passed as an argument returns false if any of the collection is a member of such class
* [ ] #my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex
* [ ] #my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex
* [ ] #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
* [ ] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
* [ ] #my_count returns the number of items in enum through enumeration::range
* [ ] #my_count counts the number of items in enum that are equal to item if an argument is given
* [ ] #my_map returns a new array with the results of running a given block once for every element in enum::range
* [ ] #my_map returns an Enumerator if no block is given
* [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
* [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
* [ ] #my_inject when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
* [ ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
* [ ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
* [ ] #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
* [ ] #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
* [ ] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject





## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @tmampa and @emmyobonyo 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

There are just 10 test cases that are failing. Kindly work on the suggested changes 👇.
### my_map
- [ ] #my_map returns an Enumerator if no block is given
- [ ] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
### my_inject
- [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
- [ ] #my_inject when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- [ ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [ ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [ ] #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [ ] #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
### multiply_els
- [ ] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
- All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.
- Congratulations on the splendid job @tmampa and @emmyobonyo! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
